development:
    domain:             localhost:3000
    app_name:           Well Dressed Up
    twitter_key:        
    twitter_secret:     
    facebook_key:       
    facebook_secret:    
    linked_in_key:      
    linked_in_secret:   

test:
    domain:             test.host
    app_name:           Well Dressed Up
    twitter_key:        
    twitter_secret:     
    facebook_key:       
    facebook_secret:    
    linked_in_key:      
    linked_in_secret:   

production:
    domain:             welldressedup.herokuapp.com
    app_name:           Well Dressed Up
    # FILL IN FOLLOWING LINES WITH REAL ACCOUNTS (POINTING TO HEROKU)
    # twitter_key:        
    # twitter_secret:     
    # facebook_key:       
    # facebook_secret:    
    # linked_in_key:      
    # linked_in_secret: