development:
    domain:             localhost:3000
    app_name:           Twarl
    app_description:    A choice directory of independent designer/makers, producing bespoke commissions and exclusive lines of clothing, accessories & costumes.
    twitter_key:        
    twitter_secret:     
    facebook_key:       
    facebook_secret:    
    linked_in_key:      
    linked_in_secret:   
    google_analytics:   

test:
    domain:             test.host
    app_name:           Twarl
    app_description:    A choice directory of independent designer/makers, producing bespoke commissions and exclusive lines of clothing, accessories & costumes.
    twitter_key:        
    twitter_secret:     
    facebook_key:       
    facebook_secret:    
    linked_in_key:      
    linked_in_secret:   
    google_analytics:   

production:
    domain:             twarl.herokuapp.com
    app_name:           Twarl
    app_description:    A choice directory of independent designer/makers, producing bespoke commissions and exclusive lines of clothing, accessories & costumes.
