##
# Configuration settings for use by the Rails application
# Made available via the SimpleConfig global class
# Use for settings such as mail server configurations, Amazon keys and secrets etc...
# You can use ERB too
#
# NNB: This file contains SECRETS! NOT FOR SOURCE CONTROL!!!
#
##

##
# Define shared settings
#
shared: &shared

  ## E.g. Amazon key and secret
  # s3_key: XXXXXXXXXXXXXXXXXXXX 
  # s3_secret: 12345678901234567890ABCDEFGHIJKLMNOPQRST
  example: sekret!

##
# Define settings per Rails environment, 
# provide overrides to the shared settings as needed
#
development:
  # inherit shared settings
  <<: *shared
  
test:
  # inherit shared settings
  <<: *shared


production:
  # inherit shared settings
  <<: *shared



